theme: jekyll-theme-cayman
theme: jekyll-theme-cayman

title: Extended Reality Controlled Robotic Hand and Arm
description: A University of Illinois Engineering Open House Project

github:
  
  main_page: https://nychung2.github.io/eoh22/index.html
  about_us: https://nychung2.github.io/eoh22/about_us.html
